name: Publish Python Package

on:
  push:
    tags:
      - 'v*'
  release:
    types: [published]

jobs:
  publish:
    name: Publish to GitHub Package Registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: python -m build

      - name: Publish to GitHub Package Registry
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          twine upload --repository-url https://upload.pypi.org/legacy/ dist/* 2>/dev/null || \
          twine upload --repository-url https://test.pypi.org/legacy/ dist/*